### ISSUE TITLE
NEED HELP ABOUT THIS ONE

### ISSUE THREAD

**Issue by serpentoi2** [Rosewood-Development/RoseStacker#113]
[13:44:25 WARN]: [RoseStacker] Plugin RoseStacker v1.5.20 generated an exception while executing task 223692
java.util.ConcurrentModificationException: null
        at java.util.HashMap.computeIfAbsent(HashMap.java:1229) ~[?:?]
        at dev.rosewood.rosestacker.stack.settings.EntityStackSettings.isEntity(EntityStackSettings.java:218) ~[RoseStacker.jar:?]
        at dev.rosewood.rosestacker.stack.settings.EntityStackSettings.applySpawnerSpawnedProperties(EntityStackSettings.java:333) ~[RoseStacker.jar:?]
        at dev.rosewood.rosestacker.spawning.MobSpawningMethod.createNewEntity(MobSpawningMethod.java:336) ~[RoseStacker.jar:?]
        at dev.rosewood.rosestacker.spawning.MobSpawningMethod.spawnEntitiesIntoNearbyStacks(MobSpawningMethod.java:216) ~[RoseStacker.jar:?]
        at dev.rosewood.rosestacker.spawning.MobSpawningMethod.lambda$spawn$3(MobSpawningMethod.java:156) ~[RoseStacker.jar:?]
        at dev.rosewood.rosestacker.utils.ThreadUtils.lambda$wrap$0(ThreadUtils.java:45) ~[RoseStacker.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.2.jar:git-Paper-318]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by serpentoi2** [comment]
I found the issue when you set the spawner stack to 20 then set it back to 5 thw 20 stack still remain and cause server crash

**Comment by serpentoi2** [comment]
Pleaseee make a feature that when mob spawner stack to 5 then the older mob stacker that have 20 or 50+ it will automatically converted to 5

**Comment by serpentoi2** [comment]
I got stress on my server finding solutions how to remove mob spawners on all radius...

**Comment by Esophose** [comment]
I do believe this error is fixed in the latest update, I don't really want to make it so the spawners automatically decrease their size, that would be very destructive for players.
