### ISSUE TITLE
Could not pass event CreatureSpawnEvent to RoseStacker v1.5.21

### ISSUE THREAD

**Issue by hoangxuanlam2007** [Rosewood-Development/RoseStacker#117]
I'm only using the Mob Stacker State for 4 mobs (Creeper, Zombie, Skeleton and Enderman), this is the issue that I'm facing with:

```
[16:39:47 ERROR]: Could not pass event CreatureSpawnEvent to RoseStacker v1.5.21
net.minecraft.ReportedException: Saving entity NBT
        at net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:2540) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:2374) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at dev.rosewood.rosestacker.nms.v1_20_R3.NMSHandlerImpl.saveEntityToTag(NMSHandlerImpl.java:553) ~[RoseStacker-1.5.21.jar:?]
        at dev.rosewood.rosestacker.nms.v1_20_R3.storage.NBTStackedEntityDataStorage.add(NBTStackedEntityDataStorage.java:62) ~[RoseStacker-1.5.21.jar:?]
        at dev.rosewood.rosestacker.stack.StackedEntity.lambda$increaseStackSize$0(StackedEntity.java:118) ~[RoseStacker-1.5.21.jar:?]
        at dev.rosewood.rosestacker.stack.StackedEntity.increaseStackSize(StackedEntity.java:129) ~[RoseStacker-1.5.21.jar:?]
        at dev.rosewood.rosestacker.stack.StackedEntity.increaseStackSize(StackedEntity.java:113) ~[RoseStacker-1.5.21.jar:?]
        at dev.rosewood.rosestacker.stack.StackingThread.tryStackEntity(StackingThread.java:989) ~[RoseStacker-1.5.21.jar:?]
        at dev.rosewood.rosestacker.stack.StackingThread.createEntityStack(StackingThread.java:544) ~[RoseStacker-1.5.21.jar:?]
        at dev.rosewood.rosestacker.manager.StackManager.createEntityStack(StackManager.java:249) ~[RoseStacker-1.5.21.jar:?]
        at dev.rosewood.rosestacker.listener.EntityListener.lambda$onCreatureSpawn$0(EntityListener.java:131) ~[RoseStacker-1.5.21.jar:?]
        at dev.rosewood.rosestacker.listener.EntityListener.onCreatureSpawn(EntityListener.java:140) ~[RoseStacker-1.5.21.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor564.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2176]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:799) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:703) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1782) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1704) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.lambda$addFreshEntityWithPassengers$0(ServerLevelAccessor.java:16) ~[?:?]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at net.minecraft.world.level.ServerLevelAccessor.addFreshEntityWithPassengers(ServerLevelAccessor.java:16) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tryAddFreshEntityWithPassengers(ServerLevel.java:1805) ~[?:?]
        at net.minecraft.world.level.BaseSpawner.serverTick(BaseSpawner.java:194) ~[?:?]
        at net.minecraft.world.level.block.entity.SpawnerBlockEntity.serverTick(SpawnerBlockEntity.java:55) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1184) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1136) ~[?:?]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1347) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:960) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1759) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1638) ~[?:?]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1636) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.persistence.CraftPersistentDataContainer.toTagCompound(CraftPersistentDataContainer.java:143) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.storeBukkitValues(CraftEntity.java:989) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.world.entity.Entity.saveWithoutId(Entity.java:2504) ~[purpur-1.20.4.jar:git-Purpur-2176]
        ... 39 more
```

Please help me!

**Comment by Esophose** [comment]
This can happen sometimes when saving the entity's data to the stack. It shouldn't negatively affect anything and you can just ignore it for now. I'll think of ways I can try to suppress the error
