### ISSUE TITLE
Bug at vilager stacking

### ISSUE THREAD

**Issue by ZuRiKanHD** [Rosewood-Development/RoseStacker#120]
Hello,

If I want to adjust the stacking in the villagers via the config, this leads to a recurring console error

Config:

`VILLAGER:
  enabled: true
  display-name: Dorfbewohner
  min-stack-size: -1
  max-stack-size: 5
  kill-entire-stack-on-death: default
  merge-radius: -1
  only-stack-from-spawners: default
  data-storage-type: default
  disable-all-mob-ai: default
  dont-stack-if-different-age: true
  dont-stack-if-baby: true
  dont-stack-if-trading: true
  dont-stack-if-professioned: true
  dont-stack-if-different-profession: true
  dont-stack-if-different-type: true
  dont-stack-if-different-level: true`

Error:
`[09.08 15:42:43.732] INFO: [City-1] [15:42:42 WARN]: [RoseStacker] Plugin RoseStacker v1.5.24 generated an exception while executing task 2991
[09.08 15:42:43.732] INFO: [City-1] java.lang.IncompatibleClassChangeError: Found class org.bukkit.entity.Villager$Profession, but interface was expected
[09.08 15:42:43.732] INFO: [City-1]     at dev.rosewood.rosestacker.stack.settings.conditions.entity.StackConditions.lambda$static$62(StackConditions.java:254) ~[RoseStacker.jar:?]
[09.08 15:42:43.732] INFO: [City-1]     at dev.rosewood.rosestacker.stack.settings.conditions.entity.StackConditions.lambda$registerConfig$73(StackConditions.java:279) ~[RoseStacker.jar:?]
[09.08 15:42:43.732] INFO: [City-1]     at dev.rosewood.rosestacker.stack.settings.EntityStackSettings$StackConditionEntry.apply(EntityStackSettings.java:389) ~[RoseStacker.jar:?]
[09.08 15:42:43.732] INFO: [City-1]     at dev.rosewood.rosestacker.stack.settings.EntityStackSettings.canStackWith(EntityStackSettings.java:207) ~[RoseStacker.jar:?]
[09.08 15:42:43.732] INFO: [City-1]     at dev.rosewood.rosestacker.stack.settings.EntityStackSettings.testCanStackWith(EntityStackSettings.java:190) ~[RoseStacker.jar:?]
[09.08 15:42:43.732] INFO: [City-1]     at dev.rosewood.rosestacker.stack.settings.EntityStackSettings.testCanStackWith(EntityStackSettings.java:177) ~[RoseStacker.jar:?]
[09.08 15:42:43.732] INFO: [City-1]     at dev.rosewood.rosestacker.stack.StackingThread.tryStackEntity(StackingThread.java:953) ~[RoseStacker.jar:?]
[09.08 15:42:43.732] INFO: [City-1]     at dev.rosewood.rosestacker.stack.StackingThread.stackEntities(StackingThread.java:151) ~[RoseStacker.jar:?]
[09.08 15:42:43.732] INFO: [City-1]     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496]
[09.08 15:42:43.732] INFO: [City-1]     at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-496]
[09.08 15:42:43.732] INFO: [City-1]     at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
[09.08 15:42:43.732] INFO: [City-1]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
[09.08 15:42:43.732] INFO: [City-1]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
[09.08 15:42:43.732] INFO: [City-1]     at java.lang.Thread.run(Thread.java:1583) ~[?:?]
`

**Comment by Esophose** [comment]
Some of the villager conditions currently look broken, thanks for reporting
