### ISSUE TITLE
Console Error SheepRegrowWoolEvent

### ISSUE THREAD

**Issue by PirataGu** [Rosewood-Development/RoseStacker#121]
[15:39:14 ERROR]: Could not pass event SheepRegrowWoolEvent to RoseStacker v1.5.24
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Double (java.lang.Integer and java.lang.Double are in module java.base of loader 'bootstrap')
        at dev.rosewood.rosestacker.stack.settings.EntityStackSettings$EntitySetting.getDouble(EntityStackSettings.java:449) ~[RoseStacker-1.5.24.jar:?]
        at dev.rosewood.rosestacker.listener.EntityListener.onSheepRegrowWool(EntityListener.java:578) ~[RoseStacker-1.5.24.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor954.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2176]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.animal.Sheep.ate(Sheep.java:441) ~[?:?]
        at net.minecraft.world.entity.ai.goal.EatBlockGoal.tick(EatBlockGoal.java:91) ~[?:?]
        at net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:63) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tickRunningGoals(GoalSelector.java:156) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:147) ~[?:?]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:961) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3508) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:707) ~[?:?]
        at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:155) ~[?:?]
        at net.minecraft.world.entity.animal.Animal.aiStep(Animal.java:64) ~[?:?]
        at net.minecraft.world.entity.animal.Sheep.aiStep(Sheep.java:186) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3157) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:463) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1492) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:940) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:917) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1759) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Esophose** [comment]
Hello, this question was properly answered with a solution here https://github.com/Rosewood-Development/RoseLoot/issues/35#issuecomment-2278842675. Are you still having trouble with it?

**Comment by PirataGu** [comment]
oh sorry I didnt received the email with the answer to the problem
