### ISSUE TITLE
1.21.1 | NMSAdapter is nulll

### ISSUE THREAD

**Issue by myavuzokumus** [Rosewood-Development/RoseStacker#123]
```
[05:28:18 ERROR]: Error occurred while enabling RoseStacker v1.5.24 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at RoseStacker-1.5.24.jar/dev.rosewood.rosestacker.stack.settings.EntityStackSettings.<init>(EntityStackSettings.java:86) ~[RoseStacker-1.5.24.jar:?]
        at RoseStacker-1.5.24.jar/dev.rosewood.rosestacker.manager.StackSettingManager.lambda$reload$1(StackSettingManager.java:115) ~[RoseStacker-1.5.24.jar:?]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at RoseStacker-1.5.24.jar/dev.rosewood.rosestacker.manager.StackSettingManager.reload(StackSettingManager.java:94) ~[RoseStacker-1.5.24.jar:?]
        at RoseStacker-1.5.24.jar/dev.rosewood.rosestacker.lib.rosegarden.RosePlugin.getManager(RosePlugin.java:274) ~[RoseStacker-1.5.24.jar:?]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
        at RoseStacker-1.5.24.jar/dev.rosewood.rosestacker.lib.rosegarden.RosePlugin.reload(RosePlugin.java:215) ~[RoseStacker-1.5.24.jar:?]
        at RoseStacker-1.5.24.jar/dev.rosewood.rosestacker.RoseStacker.reload(RoseStacker.java:109) ~[RoseStacker-1.5.24.jar:?]
        at RoseStacker-1.5.24.jar/dev.rosewood.rosestacker.lib.rosegarden.RosePlugin.onEnable(RosePlugin.java:123) ~[RoseStacker-1.5.24.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "dev.rosewood.rosestacker.nms.NMSHandler.supportsEmptySpawners()" because the return value of "dev.rosewood.rosestacker.nms.NMSAdapter.getHandler()" is null
        at RoseStacker-1.5.24.jar/dev.rosewood.rosestacker.stack.settings.conditions.entity.StackConditions.<clinit>(StackConditions.java:197) ~[RoseStacker-1.5.24.jar:?]
        ... 21 more
```

**Comment by myavuzokumus** [comment]
Anyway, it has already been fixed in the dev build.
