### ISSUE TITLE
1.21.3 Console Spam issue 

### ISSUE THREAD

**Issue by CryZii** [Rosewood-Development/RoseStacker#137]
[15:25:31 WARN]: [RoseStacker] Plugin RoseStacker v1.5.30-SNAPSHOT generated an exception while executing task 97
java.lang.IllegalStateException: zip file closed
        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:846) ~[?:?]
        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:338) ~[?:?]
        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:516) ~[?:?]
        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:144) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.entrypoint.classloader.group.SimpleListPluginClassLoaderGroup.lookupClass(SimpleListPluginClassLoaderGroup.java:46) ~[paper-1.21.3.jar:1.21.3-82-5a60ffb]
        at io.papermc.paper.plugin.entrypoint.classloader.group.SimpleListPluginClassLoaderGroup.getClassByName(SimpleListPluginClassLoaderGroup.java:37) ~[paper-1.21.3.jar:1.21.3-82-5a60ffb]
        at io.papermc.paper.plugin.entrypoint.classloader.group.LockingClassLoaderGroup.getClassByName(LockingClassLoaderGroup.java:34) ~[paper-1.21.3.jar:1.21.3-82-5a60ffb]
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:140) ~[paper-1.21.3.jar:1.21.3-82-5a60ffb]
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:107) ~[paper-1.21.3.jar:1.21.3-82-5a60ffb]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at RoseStacker-1.5.30-SNAPSHOT.jar/dev.rosewood.rosestacker.hook.NPCsHook.isNPC(NPCsHook.java:165) ~[RoseStacker-1.5.30-SNAPSHOT.jar:?]
        at RoseStacker-1.5.30-SNAPSHOT.jar/dev.rosewood.rosestacker.stack.StackedEntity.checkNPC(StackedEntity.java:95) ~[RoseStacker-1.5.30-SNAPSHOT.jar:?]
        at RoseStacker-1.5.30-SNAPSHOT.jar/dev.rosewood.rosestacker.stack.StackingThread.tryStackEntity(StackingThread.java:934) ~[RoseStacker-1.5.30-SNAPSHOT.jar:?]
        at RoseStacker-1.5.30-SNAPSHOT.jar/dev.rosewood.rosestacker.stack.StackingThread.stackEntities(StackingThread.java:152) ~[RoseStacker-1.5.30-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.3.jar:1.21.3-82-5a60ffb]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.3.jar:1.21.3-82-5a60ffb]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.21.3.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Esophose** [comment]
This is caused by a disabled plugin on your server RoseStacker is trying to access. Fix whatever is red in /plugins. Also, that version of RoseStacker doesn't support 1.21.3. Try [this](https://jenkins.rosewooddev.io/job/Rosewood%20Development/job/RoseStacker/259/artifact/build/libs/RoseStacker-1.5.30-SNAPSHOT.jar) one

**Comment by CryZii** [comment]
ah thank you, i updated my other plugins and seems its not spamming anymore
