### ISSUE TITLE
Failed saving entity NBT Villager

### ISSUE THREAD

**Issue by ItzEnderArkail** [Rosewood-Development/RoseStacker#34]
im getting this annoying error in the console at random times

MC Version: purpur 1.16.5
Plugin Version: 1.3.1

logs:
[04:34:06 WARN]: [RoseStacker] Plugin RoseStacker v1.3.1 generated an exception while executing task 1694652
net.minecraft.server.v1_16_R3.ReportedException: Saving entity NBT
        at net.minecraft.server.v1_16_R3.Entity.save(Entity.java:2035) ~[patched_1.16.5.jar:git-Purpur-1171]
        at dev.rosewood.rosestacker.nms.v1_16_R3.object.CompactNBTImpl.<init>(CompactNBTImpl.java:31) ~[?:?]
        at dev.rosewood.rosestacker.nms.v1_16_R3.NMSHandlerImpl.createCompactNBT(NMSHandlerImpl.java:421) ~[?:?]
        at dev.rosewood.rosestacker.stack.StackingThread.lambda$stackEntities$2(StackingThread.java:154) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Purpur-1171]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalStateException: VillagerAcquireTradeEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:612) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.EntityVillagerAbstract.a(EntityVillagerAbstract.java:291) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.EntityVillager.eW(EntityVillager.java:978) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.EntityVillagerAbstract.getOffers(EntityVillagerAbstract.java:134) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.EntityVillagerAbstract.saveData(EntityVillagerAbstract.java:197) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.EntityVillager.saveData(EntityVillager.java:565) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.Entity.save(Entity.java:1986) ~[patched_1.16.5.jar:git-Purpur-1171]
        ... 9 more

**Comment by Esophose** [comment]
I am assuming this is fixed in the latest versions of the plugin, if this is still an issue please create a new ticket.
