### ISSUE TITLE
issue with mythicmobs causing console spam

### ISSUE THREAD

**Issue by BookWyrm114** [Rosewood-Development/RoseStacker#35]
[15:02:41 FATAL]: Thread Craft Scheduler Thread - 216 - RoseStacker failed thread check for reason: Asynchronous Chunk getEntities call
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.17.1.jar:git-Purpur-1332]
	at net.minecraft.server.level.WorldServer.getEntities(WorldServer.java:2360) ~[patched_1.17.1.jar:git-Purpur-1332]
	at net.minecraft.server.level.WorldServer.getEntity(WorldServer.java:1804) ~[patched_1.17.1.jar:git-Purpur-1332]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.getEntity(CraftServer.java:2267) ~[patched_1.17.1.jar:git-Purpur-1332]
	at org.bukkit.Bukkit.getEntity(Bukkit.java:1753) ~[patched_1.17.1.jar:git-Purpur-1332]
	at io.lumine.xikage.mythicmobs.adapters.bukkit.BukkitServer.getEntity(BukkitServer.java:106) ~[MythicMobs-5.0.0-alpha1.jar:?]
	at io.lumine.xikage.mythicmobs.mobs.ActiveMob.loadSaved(ActiveMob.java:184) ~[MythicMobs-5.0.0-alpha1.jar:?]
	at io.lumine.xikage.mythicmobs.mobs.MobRegistry.isActiveMob(MobRegistry.java:47) ~[MythicMobs-5.0.0-alpha1.jar:?]
	at io.lumine.xikage.mythicmobs.mobs.MobManager.isActiveMob(MobManager.java:283) ~[MythicMobs-5.0.0-alpha1.jar:?]
	at io.lumine.xikage.mythicmobs.mobs.MobManager.isActiveMob(MobManager.java:274) ~[MythicMobs-5.0.0-alpha1.jar:?]
	at io.lumine.xikage.mythicmobs.api.bukkit.BukkitAPIHelper.isMythicMob(BukkitAPIHelper.java:89) ~[MythicMobs-5.0.0-alpha1.jar:?]
	at dev.rosewood.rosestacker.hook.NPCsHook.isNPC(NPCsHook.java:110) ~[RoseStacker-1.3.1.jar:?]
	at dev.rosewood.rosestacker.stack.StackedEntity.checkNPC(StackedEntity.java:74) ~[RoseStacker-1.3.1.jar:?]
	at dev.rosewood.rosestacker.stack.StackingThread.tryStackEntity(StackingThread.java:682) ~[RoseStacker-1.3.1.jar:?]
	at dev.rosewood.rosestacker.stack.StackingThread.lambda$stackEntities$2(StackingThread.java:138) ~[RoseStacker-1.3.1.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) [patched_1.17.1.jar:git-Purpur-1332]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [patched_1.17.1.jar:git-Purpur-1332]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.17.1.jar:git-Purpur-1332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[15:02:41 WARN]: [RoseStacker] Plugin RoseStacker v1.3.1 generated an exception while executing task 784994
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[patched_1.17.1.jar:git-Purpur-1332]
	at net.minecraft.server.level.WorldServer.getEntities(WorldServer.java:2360) ~[patched_1.17.1.jar:git-Purpur-1332]
	at net.minecraft.server.level.WorldServer.getEntity(WorldServer.java:1804) ~[patched_1.17.1.jar:git-Purpur-1332]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.getEntity(CraftServer.java:2267) ~[patched_1.17.1.jar:git-Purpur-1332]
	at org.bukkit.Bukkit.getEntity(Bukkit.java:1753) ~[patched_1.17.1.jar:git-Purpur-1332]
	at io.lumine.xikage.mythicmobs.adapters.bukkit.BukkitServer.getEntity(BukkitServer.java:106) ~[MythicMobs-5.0.0-alpha1.jar:?]
	at io.lumine.xikage.mythicmobs.mobs.ActiveMob.loadSaved(ActiveMob.java:184) ~[MythicMobs-5.0.0-alpha1.jar:?]
	at io.lumine.xikage.mythicmobs.mobs.MobRegistry.isActiveMob(MobRegistry.java:47) ~[MythicMobs-5.0.0-alpha1.jar:?]
	at io.lumine.xikage.mythicmobs.mobs.MobManager.isActiveMob(MobManager.java:283) ~[MythicMobs-5.0.0-alpha1.jar:?]
	at io.lumine.xikage.mythicmobs.mobs.MobManager.isActiveMob(MobManager.java:274) ~[MythicMobs-5.0.0-alpha1.jar:?]
	at io.lumine.xikage.mythicmobs.api.bukkit.BukkitAPIHelper.isMythicMob(BukkitAPIHelper.java:89) ~[MythicMobs-5.0.0-alpha1.jar:?]
	at dev.rosewood.rosestacker.hook.NPCsHook.isNPC(NPCsHook.java:110) ~[RoseStacker-1.3.1.jar:?]
	at dev.rosewood.rosestacker.stack.StackedEntity.checkNPC(StackedEntity.java:74) ~[RoseStacker-1.3.1.jar:?]
	at dev.rosewood.rosestacker.stack.StackingThread.tryStackEntity(StackingThread.java:682) ~[RoseStacker-1.3.1.jar:?]
	at dev.rosewood.rosestacker.stack.StackingThread.lambda$stackEntities$2(StackingThread.java:138) ~[RoseStacker-1.3.1.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1332]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) [patched_1.17.1.jar:git-Purpur-1332]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.17.1.jar:git-Purpur-1332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Esophose** [comment]
What version of MythicMobs are you using? It's possible they changed something that broke compatibility, because it used used to work fine

**Comment by BookWyrm114** [comment]
I'm using version 5.0.0-SNAPSHOT-5145f853
